version: '3'

services:
  dash_app:
    build:
      context: .
    ports:
      - "8050:8050"
    depends_on:
      - transfermarkt_api
    networks:
      - app-network
    volumes:
      - ./:/app  # For live code reloading during development

  transfermarkt_api:
    build:
      context: ./transfermarkt-api
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./transfermarkt-api:/app  # For live code reloading if needed

networks:
  app-network:
      driver: bridge