version: '3'

services:
  dash_app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - transfermarkt_api
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ./:/app  # For live code reloading during development

  transfermarkt_api:
    build:
      context: ./transfermarkt-api
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DASH_DEBUG_MODE=False
    volumes:
      - ./transfermarkt-api:/app  # For live code reloading if needed

networks:
  app-network:
      driver : bridge 



