version: '3'

services:
  dash_app:
    build:
      context: .
    ports:
      - "8050:8050"
    depends_on:
      - transfermarkt_api
    networks:
      - botola_app-network
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - TRANSFERMARKT_API_URL=http://transfermarkt-api:8000  # Environment variable to connect to the transfermarkt-api service

    volumes:
      - ./:/app  # For live code reloading during development

  transfermarkt_api:
    build:
      context: ./transfermarkt-api
    ports:
      - "8000:8000"
    networks:
      - botola_app-network
    environment:
      - FLASK_DEBUG_MODE=False
      - ENV FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./transfermarkt-api:/app  # For live code reloading if needed

networks:
  app-network:
      driver : bridge 



